tunnel: #SSH Tunnel
  enable: false # Default false. If tgi or jupyter is enable, always enabled

jupyter:
  enable: true # Default false.
  singularity: python-jupyter.sif                                   # The singularity image must exists in $GPFS_SINGULARITY_IMAGE_REGISTRY_PATH.

tgi: # Text generation inference
  enable: true # Default false.
  singularity: text-generation-inference.singularity.1.4.4.sif # The singularity image must exists in $GPFS_SINGULARITY_IMAGE_REGISTRY_PATH.
  model: Mistral-7B-Instruct-v0.3 # The model must exists in $GPFS_MODEL_REGISTRY_PATH.
  # params: --max-input-length 8000 --max-batch-prefill-tokens 8000 --max-total-tokens 12000 # (TGI) Must be valid parameters, otherwise tgi will throw an error
  params: --max-input-length 8000 --max-batch-prefill-tokens 8000 --max-total-tokens 12000 # (VLM) Must be valid parameters, otherwise tgi will throw an error
  vllm: true # If True uses vLLM api to deploy, otherwise text generation inferences. (Default: false)


# Enable singularity get access to custom image from $GPFS_SINGULARITY_IMAGE_REGISTRY_PATH.
# You will have access to this image through $JOB_SINGULARITY_IMAGE env variable.

singularity:
  enable: true # Default false. 
  # name: my-custom-image.sif # Default: <repo>/<branch>. For current or another <repo>/<branch> do not add .sif.
  sandbox: false # Default: false. Only needed while creating, it will save image as a sandbox if true, otherwise as a singularity.

# Following conditions only applies if the name of singularity (name:) is equal to current <repo>/<branch> and matches the current repo, branch.
  # If the image does not exists or is a old version , it will create new image from the dockerfile you have in your repository.
  # If already exists, will install all requirements from requirement.txt.
