tunnel:
  enable: false # Default false. If tgi or jupyter is enable, always enable

jupyter:
  enable: true # Default false.
  singularity: python-jupyter.sif                                   # The singularity image must exists in $GPFS_SINGULARITY_IMAGE_REGISTRY_PATH.

tgi: # Text generation infrence
  enable: true # Default false.
  singularity: text-generation-inference.singularity.1.4.4.sif # The singularity image must exists in $GPFS_SINGULARITY_IMAGE_REGISTRY_PATH.
  model: Mistral-7B-Instruct-v0.3 # The model must exists in $GPFS_MODEL_REGISTRY_PATH.
  params: --max-input-length 8000 --max-batch-prefill-tokens 8000 --max-total-tokens 12000 # Must be valid parameters, otherwise tgi will throw error

# Un comment to get access to custom image from $GPFS_SINGULARITY_IMAGE_REGISTRY_PATH. Default: <current_repo>/<current_branch>.
# You will have access to this image through $GPFS_JUPYTER_SINGULARITY. 
# singularity: python-jupyter.sif