githubConfigUrl: https://github.com/langtech-bsc
githubConfigSecret: magma-github-app
maxRunners: 5
minRunners: 1
runnerGroup: default
runnerScaleSetName: magma-arc
containerMode:
  type: dind
template:
  spec:
    containers:
      - name: runner
        image: projecteaina/actions-runner:b084f07
        command:
          - /home/runner/run.sh
