name: "Set secrets or vars to env"
description: "GitHub Action to set secrets or vars to env. Also verifies that required secrets are not missing"
author: Ankush Raj <https://www.bsc.es/rana-ankush>

inputs:
  json:
    description: "Vars, secrets or any json with key values."
    required: false
  name:
    description: "Whether it's a variable, secret, or any other. Default secret."
    default: "secret"
    required: false
  must_exist:
    description: "These keys must exist with a value; otherwise, an error will be thrown (E.g, 'key1,key2,...')."
    required: false
  exclude:
    description: "Variables those are not going to be set as env avariables (E.g, 'key1,key3,...')."
    required: false
runs:
  using: "node20"
  main: "dist/index.js"
