name: Addons
description: "GitHub Action to modify sbatch with addons"
author: Ankush Raj <https://www.bsc.es/rana-ankush>

inputs:
  file:
    description: "File where the changes will be update"
    required: true
  
  jupyter:
    description: "Inject jupter"
    required: false
    default: false
  
  tgi:
    description: "Inject tgi"
    required: false
    default: false

  vlm:
    description: "Inject vlm"
    required: false
    default: false

  sleep: 
    description: "Add sleep at the end of file"
    required: false
    default: false
    
runs:
  using: "composite"
  steps:

    - name: Set globals
      id: globals
      shell: bash
      run: |
        echo "START_LINE=# --- IMPORTANT: DO NOT DELETE OR MODIFY THE FOLLOWING LINE ---" >> "${GITHUB_OUTPUT}"
        echo "LAST_LINE=# --- IMPORTANT: DO NOT DELETE OR MODIFY THE ABOVE LINE ---" >> "${GITHUB_OUTPUT}"

    - name: Check file
      shell: bash
      run: |
        if [ -f "${{inputs.file}}" ]; then
          echo "" >> file.tmp
          echo "${{ steps.globals.outputs.START_LINE }}" > file.tmp
          echo "" >> file.tmp
        else 
          echo "File '${{inputs.file}}' does not exist" && exit 1
        fi

    - name: Set requierd directives
      shell: bash
      run: |
        echo "" >> file.tmp
        cat ${{ github.action_path }}/directives.sh >> file.tmp
        echo "" >> file.tmp
        echo "Set directives done."

    - name: Set jupiter
      shell: bash
      if: ${{ inputs.jupyter == 'true' }}
      run: |
        echo "" >> file.tmp
        cat ${{ github.action_path }}/jupyter.sh >> file.tmp
        echo "" >> file.tmp
        echo "Set jupiter done."

    - name: Set tgi
      shell: bash
      if: ${{ inputs.tgi == 'true' }}
      run: |
        echo "" >> file.tmp
        cat ${{ github.action_path }}/tgi.sh >> file.tmp
        echo "" >> file.tmp
        echo "Set tgi done."

    - name: Set vlm
      shell: bash
      if: ${{ inputs.vlm == 'true' }}
      run: |
        echo "" >> file.tmp
        cat ${{ github.action_path }}/vlm.sh >> file.tmp
        echo "" >> file.tmp
        echo "Set vlm done."


    - name: Set last line
      shell: bash
      run: |
        echo "${{ steps.globals.outputs.LAST_LINE }}" >> file.tmp
        echo "" >> file.tmp
        echo "" >> file.tmp

    - name: Update file
      shell: bash
      run: |
        last_sbatch_line=$(grep -n '^#SBATCH' "${{inputs.file}}" | tail -1 | cut -d: -f1) # get last line number of #SBATCH
        
        # Split the original sbatch file into two parts
        head -n "$last_sbatch_line" "${{inputs.file}}" > temp_head.sh
        echo "" >> temp_head.sh
        tail -n +$((last_sbatch_line + 1)) "${{inputs.file}}" > temp_tail.sh

        cat temp_head.sh file.tmp temp_tail.sh > ${{inputs.file}}
        echo "File updated"

    - name: Set sleep line
      if: ${{ inputs.sleep == 'true' }}
      shell: bash
      run: |
        echo "" >> ${{inputs.file}}
        echo "${{ steps.globals.outputs.FIRST_LINE }}" >> ${{inputs.file}}
        echo "" >> ${{inputs.file}}
        echo "echo Execute sleep" >> ${{inputs.file}}
        echo "sleep 30d" >> ${{inputs.file}}
        echo "" >> ${{inputs.file}}
        echo "${{ steps.globals.outputs.LAST_LINE }}" >> ${{inputs.file}}

    - name: Clean all
      shell: bash
      run: rm -rf temp_head.sh temp_tail.sh file.tmp



    
  
