name: Actions Runner Docker Image CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'actions-runner-controller/runner/Dockerfile'
    tags-ignore:
      - "*"
jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Set short sha
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - 
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: actions-runner-controller/runner/
          push: true
          tags: projecteaina/actions-runner:latest, projecteaina/actions-runner:${{ steps.vars.outputs.sha_short }}
      -
        name: Update Image Version in the related HelmChart values.yaml
        uses: OpsVerseIO/image-updater-action@0.1.0
        with:
          valueFile: 'actions-runner-controller/charts/runner-scale-set/values.yaml'
          propertyPath: 'template.spec.containers[0].image'
          value: projecteaina/actions-runner:${{ steps.vars.outputs.sha_short }}
          branch: update-chart-image/${{ steps.vars.outputs.sha_short }}
          targetBranch: main
          masterBranchName: main
          createPR: true
          description: 'Update Actions Runner Docker Image to projecteaina/actions-runner:${{ steps.vars.outputs.sha_short }}'
          message: 'Update Actions Runner Docker Image to projecteaina/actions-runner:${{ steps.vars.outputs.sha_short }}'