name: Enhanced Launch job and docker

on:
  workflow_call:
    inputs:
      runs_on:
        required: false
        type: string
        default: magma-runner-set

jobs:
  pre-job:
    uses: langtech-bsc/magma/.github/workflows/pre_job_per_branch.yml@main
    secrets: inherit
    with:
      runs_on: ${{inputs.runs_on}}
      check_running_job: true

  docker2tar:
    if: ${{contains(fromJson('["true", true]'), needs.pre-job.outputs.create_singularity) }}
    needs:  pre-job
    uses: langtech-bsc/magma/.github/workflows/docker2tar.yml@main
    secrets: inherit
    with:
      runs_on: 'shell-ssd'
      image: ${{ needs.pre-job.outputs.job_name }}
      path: ${{ needs.pre-job.outputs.job_path }}/build

  build:
    needs:  [pre-job, docker2tar]
    uses: langtech-bsc/magma/.github/workflows/launch_job.yml@main
    secrets: inherit
    with:
      job_path: ${{ needs.pre-job.outputs.job_path }}/build
      job_name: ${{ needs.pre-job.outputs.job_name }}
      singularity: ${{ needs.pre-job.outputs.job_name }}
      remote_job: "build"
      remote_job_sandbox: ${{fromJson(needs.pre-job.outputs.sandbox)}}

  # install:
  #   if: |
  #     always() &&
  #     needs.pre-job.result == 'success' &&
  #     contains(fromJson('["true", true]'), needs.pre-job.outputs.install_reqs) &&
  #     (needs.docker2tar.result == 'success' || needs.docker2tar.result == 'skipped') &&
  #     (needs.build.result == 'success' || needs.build.result == 'skipped') 

  #   needs:  [pre-job, docker2tar, build]
  #   uses: langtech-bsc/magma/.github/workflows/install_requirements_online.yml@main
  #   secrets: inherit
  #   with:
  #     job_path: ${{ needs.pre-job.outputs.job_path }}/install
  #     job_name: ${{ needs.pre-job.outputs.job_name }}
  #     image: ${{ needs.pre-job.outputs.singularity }}
  #     old_image: ${{ needs.pre-job.outputs.old_image }}
  #     remote_job: "install-online"
