name: Docker to singularity y branch

on:
  workflow_call:
    inputs:
      runs_on:
        required: false
        type: string
        default: magma-runner-set

jobs:
  pre-job:
    uses: langtech-bsc/magma/.github/workflows/pre_job_per_branch.yml@41-install-python-and-apt-packages-in-sandbox
    secrets: inherit
    with:
      runs_on: ${{inputs.runs_on}}
      check_running_job: true

  docker2tar:
    if: ${{contains(fromJson('["true", true]'), needs.pre-job.outputs.create_singularity) }}
    needs:  pre-job
    uses: langtech-bsc/magma/.github/workflows/docker2tar.yml@41-install-python-and-apt-packages-in-sandbox
    secrets: inherit
    with:
      image: ${{needs.pre-job.outputs.branch}}
      path: ${{ needs.pre-job.outputs.job_path }}/build

  build:
    needs:  [pre-job, docker2tar]
    uses: langtech-bsc/magma/.github/workflows/launch_job.yml@41-install-python-and-apt-packages-in-sandbox
    secrets: inherit
    with:
      job_path: ${{ needs.pre-job.outputs.job_path }}/build
      job_name: ${{ needs.pre-job.outputs.job_name }}
      singularity: ${{ needs.pre-job.outputs.branch }}
      remote_job: "build"
      remote_job_sandbox: ${{needs.pre-job.outputs.sandbox}}
