name: Make singularity
#run-name: ${{ github.actor }} is executing Make singularity 🚀

on:
  workflow_call:
    inputs:
      runs_on:
        required: false
        type: string
        default: shell
  
jobs:
  docker2singularity:
    timeout-minutes: 43200
    runs-on: ${{ inputs.runs_on }}
    steps:
      - name: Set envs
        run: echo "JOB_SINGULARITY_IMAGE=$(echo ${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}.sif | awk '{print tolower($0)}')" >> $GITHUB_ENV


      - uses: actions/checkout@v4

      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{secrets.SSH_PRIVATE_KEY}}

      - name: Build docker image
        run: docker build . --no-cache -t user/$JOB_SINGULARITY_IMAGE:latest
          
      - name: Save docker image
        run: |
          docker save user/$JOB_SINGULARITY_IMAGE:latest -o singularity-$JOB_SINGULARITY_IMAGE.tar 
          docker image rm user/$JOB_SINGULARITY_IMAGE:latest

      - name: Singularity build
        run: |
          singularity build --force $JOB_SINGULARITY_IMAGE docker-archive:singularity-$JOB_SINGULARITY_IMAGE.tar
          rm singularity-$JOB_SINGULARITY_IMAGE.tar

      - name: Push image
        run: |
          scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $JOB_SINGULARITY_IMAGE ${{secrets.REMOTE_USER}}@${{secrets.REMOTE_HOST}}:${{ vars.GPFS_SINGULARITY_IMAGE_REGISTRY_PATH }}
          rm $JOB_SINGULARITY_IMAGE
        # ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${{secrets.REMOTE_USER}}@${{secrets.REMOTE_HOST}} "cd ${{ vars.GPFS_SINGULARITY_IMAGE_REGISTRY_PATH }} && rm -rf $JOB_SINGULARITY_IMAGE"
        # tar czf - $JOB_SINGULARITY_IMAGE | ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${{secrets.REMOTE_USER}}@${{secrets.REMOTE_HOST}} "cd ${{ vars.GPFS_SINGULARITY_IMAGE_REGISTRY_PATH }} && tar xzvf - $JOB_SINGULARITY_IMAGE"

