name: Docker to singularity by branch name

on:
  workflow_call:
    inputs:
      runs_on:
        required: false
        type: string
        default: shell-ssd

jobs:
  pre-job:
    uses: langtech-bsc/magma/.github/workflows/pre_job_per_branch.yml@main
    secrets: inherit
    with:
      runs_on: ${{inputs.runs_on}}
      check_running_job: true

  docker2tar:
    needs:  pre-job
    uses: langtech-bsc/magma/.github/workflows/docker2tar.yml@main
    secrets: inherit
    with:
      image: ${{needs.pre-job.outputs.branch}}
      path: ${{ needs.pre-job.outputs.job_path }}/build

  build:
    needs:  [pre-job, docker2tar]
    uses: langtech-bsc/magma/.github/workflows/launch_job.yml@main
    secrets: inherit
    with:
      job_path: ${{ needs.pre-job.outputs.job_path }}/build
      job_name: ${{ needs.pre-job.outputs.job_name }}
      singularity: ${{ needs.pre-job.outputs.branch }}
      remote_job: "build"
      remote_job_sandbox: false
