name: Enhanced Launch job

on:
  workflow_call:
    inputs:
      runs_on:
        required: false
        type: string
        default: magma-runner-set

      local-repo: 
        required: false
        type: boolean
        default: false
      
jobs:
  pre-job:
    uses: ./.github/workflows/pre_job_per_branch.yml
    secrets: inherit
    with:
      runs_on: ${{inputs.runs_on}}
      check_running_job: true

      
  launch-job:
      if: ${{ needs.pre-job.result == 'success' && inputs.local-repo == false }}
      needs: pre-job
      uses: ./.github/workflows/launch_job.yml
      secrets: inherit
      with:
        runs_on: ${{ inputs.runs_on }}
        job_path: ${{ needs.pre-job.outputs.job_path }}
        job_name: ${{ needs.pre-job.outputs.job_name }}
        enable_tunnel: ${{ fromJson(needs.pre-job.outputs.enable_tunnel) }}
        enable_jupyter: ${{ fromJson(needs.pre-job.outputs.enable_jupyter) }}
        jupyter_singularity: ${{ needs.pre-job.outputs.jupyter_singularity }}
        enable_tgi: ${{ fromJson(needs.pre-job.outputs.enable_tgi) }}
        tgi_singularity: ${{ needs.pre-job.outputs.tgi_singularity }}
        tgi_model: ${{ needs.pre-job.outputs.tgi_model }}
        tgi_params: ${{ needs.pre-job.outputs.tgi_params }}
        singularity: ${{ needs.pre-job.outputs.singularity }}