name: Launch job

on:
  workflow_call:
    inputs:
      runs_on:
        required: false
        type: string
        default: ubuntu-latest

jobs:
    launch-job:
        uses: langtech-bsc/magma/.github/workflows/launch_job.yml@1-initial-template
        with: 
            runs_on: ${{ inputs.runs_on }}
            enable_tunnel: false
