name: Enhanced Launch job

on:
  workflow_call:
    inputs:
      runs_on:
        required: false
        type: string
        default: magma-runner-set
      
jobs:
  pre-job:
    uses: ./.github/workflows/pre_job_per_branch.yml #main
    secrets: inherit
    with:
      runs_on: ${{inputs.runs_on}}
      check_running_job: true

  launch-job:
      needs: pre-job
      uses: ./.github/workflows/launch_job.yml #main
      secrets: inherit
      with:
        runs_on: ${{ inputs.runs_on }}
        job_path: ${{ needs.pre-job.outputs.job_path }}
        job_name: ${{ needs.pre-job.outputs.job_name }}
        slrum_sbatch_params: ${{ needs.pre-job.outputs.slrum_sbatch_params }}
        
        enable_tunnel: ${{ fromJson(needs.pre-job.outputs.enable_tunnel) }}
        enable_jupyter: ${{ fromJson(needs.pre-job.outputs.enable_jupyter) }}
        jupyter_singularity: ${{ needs.pre-job.outputs.jupyter_singularity }}
        enable_tgi: ${{ fromJson(needs.pre-job.outputs.enable_tgi) }}
        tgi_singularity: ${{ needs.pre-job.outputs.tgi_singularity }}
        tgi_model: ${{ needs.pre-job.outputs.tgi_model }}
        tgi_params: ${{ needs.pre-job.outputs.tgi_params }}

        enable_vllm: ${{ fromJson(needs.pre-job.outputs.enable_vllm) }}
        vllm_singularity: ${{ needs.pre-job.outputs.vllm_singularity }}
        vllm_model: ${{ needs.pre-job.outputs.vllm_model }}
        vllm_params: ${{ needs.pre-job.outputs.vllm_params }}
        
        singularity: ${{ needs.pre-job.outputs.singularity }}
