name: Enhanced Launch job

on:
  workflow_call:
    inputs:
      runs_on:
        required: True
        type: string
      job_id:
        required: false
        type: string
      job_name:
        required: false
        type: string
        
    outputs:
        exists:
            description: "Whether the job exists or not"
            value: ${{ jobs.check-job.outputs.exists }}
    
jobs:
  check-job:
    runs-on: ${{ inputs.runs_on }}
    outputs:
        exists: ${{ steps.outputs.outputs.exists }}
    steps:
      - name: Check inputs not empty
        if: ${{inputs.job_id == '' && inputs.job_name == '' }}
        run: echo "Please provide job_id or job_name" && exit 1
    
      - name: Check job id and job name hace value
        if: ${{inputs.job_id != '' && inputs.job_name != '' }}
        run: echo "Please provide only one of following input job_id or job_name" && exit 1
    
      - name: Check jobs by job id
        if: ${{inputs.job_id != ''}}
        run: |
            COUNT=ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${{secrets.REMOTE_USER}}@${{secrets.REMOTE_HOST}} "squeue --name mixtral7x8b_instruct_rag-9479151212 -h" | wc -l 
            echo "COUNT=$COUNT" >> $GITHUB_ENV    
    
      - name: Check jobs by job name
        if: ${{inputs.job_name != ''}}
        run: |
            COUNT=ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${{secrets.REMOTE_USER}}@${{secrets.REMOTE_HOST}} "squeue --name mixtral7x8b_instruct_rag-9479151212 -h" | wc -l 
            echo "COUNT=$COUNT" >> $GITHUB_ENV    
          
      - name: Set outputs
        id: outputs
        run: |
            if [ "$JOB_COUNT" -eq 0 ]; then
                echo "exists=false" >> "$GITHUB_OUTPUT"
                echo "jobs-output=false"
            else
                echo "exists=true" >> "$GITHUB_OUTPUT"
            fi


