name: Install requirements online

on:
  workflow_call:
    inputs:
      runs_on:
        required: false
        type: string
        default: magma-runner-set
      old_image:
        required: true
        type: string
      image:
        required: true
        type: string
      job_path:
        required: true
        type: string

jobs:
  install-requirements-online:
    timeout-minutes: 43200
    runs-on: ${{ inputs.runs_on }}
    steps:
      - uses: actions/checkout@v4
      - uses: langtech-bsc/magma/actions/remote_job@41-install-python-and-apt-packages-in-sandbox
        with:
          job: 'install-online'
          remote_singularity_registry_path: ${{ vars.GPFS_SINGULARITY_IMAGE_REGISTRY_PATH }}
          image: ${{ inputs.image }}
          old_image: ${{ inputs.old_image }}
          remote_path: /gpfs/scratch/${{ secrets.REMOTE_GROUP }}/${{ secrets.REMOTE_USER }}/jobs/${{ inputs.job_path }}
          remote_user: ${{ secrets.REMOTE_USER}}
          remote_host: ${{ secrets.REMOTE_HOST }}
          ssh_secret_key: ${{ secrets.SSH_PRIVATE_KEY }}

