name: Test job enhanced launch job
run-name: ${{ github.actor }} is executing Test job enhanced launch job 🚀

on:
  workflow_dispatch:

jobs:
  test-workflow-job-enhanced-launch-job:
    uses: ./.github/workflows/enhanced_launch_job.yml
    secrets: inherit

      
