name: Test Action Addons
run-name: ${{ github.actor }} is executing Test Action Addons 🚀

on:
  workflow_dispatch:

jobs:
  test-action-addons:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./addons
        with:
            file: "src/launch.sh"
            jupyter: true

      - run: cat src/launch.sh

    



      
