name: Test job launch job
run-name: ${{ github.actor }} is executing Test job launch job 🚀

on:
  workflow_dispatch:

jobs:
  test-workflow-job-launch-job:
    uses: langtech-bsc/magma/.github/workflows/launch_job.yml@main
    secrets: inherit
