name: Test addons
run-name: ${{ github.actor }} is executing Test addons 🚀

on:
  workflow_dispatch:

jobs:
  test-addons-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: langtech-bsc/magma/addons@16-file-injection
        with:
            file: "src/launch.sh"
            jupyter: true

      - run: cat src/launch.sh

    



      
