name: Test workflow docker2tar
run-name: ${{ github.actor }} is executing Test workflow docker2tar 🚀

on:
  workflow_dispatch:



jobs:
  pre-job:
    uses: ./.github/workflows/pre_job_per_branch.yml
    secrets: inherit

  
  docker2tar:
    if: ${{contains(fromJson('["true", true]'), needs.pre-job.outputs.create_singularity) }}
    needs:  pre-job
    uses: ./.github/workflows/docker2tar.yml
    secrets: inherit
    with:
      image: ${{needs.pre-job.outputs.singularity}}
      path: ${{ needs.pre-job.outputs.job_path }}/build

  build:
    needs:  [pre-job, docker2tar]
    uses: ./.github/workflows/launch_job.yml
    secrets: inherit
    with:
      job_path: ${{ needs.pre-job.outputs.job_path }}/build
      job_name: ${{ needs.pre-job.outputs.job_name }}
      singularity: ${{ needs.pre-job.outputs.singularity }}
      remote_job: "build"
      remote_job_sandbox: ${{needs.pre-job.outputs.sandbox}}

  install:
    if: ${{always() && needs.pre-job.result == 'success' && contains(fromJson('["true", true]'), needs.pre-job.outputs.install_reqs)}}
    needs:  [pre-job, build]
    uses: ./.github/workflows/launch_job.yml
    secrets: inherit
    with:
      job_path: ${{ needs.pre-job.outputs.job_path }}/install
      job_name: ${{ needs.pre-job.outputs.job_name }}
      singularity: ${{ needs.pre-job.outputs.singularity }}
      old_image: ${{ needs.pre-job.outputs.old_image }}
      remote_job: "install"

  complete:
    if: ${{always()}}
    needs: [install]
    runs-on: magma-runner-set
    steps:
      - run: |
          echo "Test completed successfully"